services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5137:80"
    depends_on:
      - backend
      - question

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env

  question:
    build:
      context: ./server
      dockerfile: Dockerfile.question
    ports:
      - "3001:3001"
    env_file:
      - .env




  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command: start --all --config /etc/ngrok.yml
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    env_file:
      - .env
    ports:
      - "4040:4040"


      
